apiVersion: v1
kind: Service
metadata:
  name: book-query-service
  namespace: bookstore-ns
spec:
  selector:
    app: book-query-service
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer