apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-query-service
  namespace: bookstore-ns
spec:
  replicas: 1  # Only 1 instance as specified in the assignment
  selector:
    matchLabels:
      app: book-query-service
  template:
    metadata:
      labels:
        app: book-query-service
    spec:
      containers:
        - name: book-query-service
          image: lazydev7/book-query-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: bookstore-secrets
                  key: mongodb_uri
            - name: PORT
              value: "3000"
            - name: RECOMMENDATION_SERVICE_URL
              value: "http://18.118.230.221"  # For Gradescope submission
            - name: TIMEOUT_MS
              value: "3000"
            - name: RESET_TIMEOUT_MS
              value: "60000"
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 90
            timeoutSeconds: 5
            failureThreshold: 3
            periodSeconds: 10
          volumeMounts:
            - name: circuit-state
              mountPath: /app/circuit-state
      volumes:
        - name: circuit-state
          emptyDir: {}