apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-service
  namespace: bookstore-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-service
  template:
    metadata:
      labels:
        app: crm-service
    spec:
      containers:
        - name: crm-service
          image: lazydev7/crm-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ANDREW_ID
              value: "jfadiji"
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: bookstore-secrets
                  key: email-user
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookstore-secrets
                  key: email-password
            - name: PORT
              value: "8080"
