apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-mobile-bff
  namespace: bookstore-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore-mobile-bff
  template:
    metadata:
      labels:
        app: bookstore-mobile-bff
    spec:
      containers:
        - name: bookstore-mobile-bff
          image: lazydev7/bookstore-mobile-bff:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: CUSTOMER_SERVICE_URL
              value: "http://customer-service"
            - name: BOOK_COMMAND_SERVICE_URL
              value: "http://book-command-service"
            - name: BOOK_QUERY_SERVICE_URL
              value: "http://book-query-service"
            - name: PORT
              value: "8080"
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 90
            timeoutSeconds: 5
            failureThreshold: 3
            periodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - bookstore-mobile-bff