apiVersion: v1
kind: Service
metadata:
  name: bookstore-mobile-bff
  namespace: bookstore-ns
spec:
  selector:
    app: bookstore-mobile-bff
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer